### ISSUE TITLE
Prepare data scripts

### ISSUE THREAD

**Issue by Google0007** [xiyangcai/SEN-DAL#2]
Hello，
I am very interested in your project, 
I wonder if it is convenient for you to share the script for converting the ’Base.edf‘ and 'PSG.edf' format to the ‘npy’ format to prepare data in the first step?
Best wishes~
Looking forward to your reply,
Thanks in advance!

**Comment by xiyangcai** [comment]
Hi,

For the script for converting .edf to the format in this repo, you can refer to https://github.com/ziyujia/GraphSleepNet/issues/2.
